'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class acciones
    Public Property idAccion As Integer
    Public Property descri As String

    Public Overridable Property movimientos As ICollection(Of movimientos) = New HashSet(Of movimientos)

End Class
