'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace MaterialesWPF

    Partial Public Class estados
        Public Property IdEstado As Integer
        Public Property descri As String
    
        Public Overridable Property materiales As ICollection(Of materiales) = New HashSet(Of materiales)
    
    End Class

End Namespace
