'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class movimientos
    Public Property idMovimiento As Integer
    Public Property idMaterial As Integer
    Public Property accion As Integer
    Public Property fecha As Date

    Public Overridable Property acciones As acciones
    Public Overridable Property materiales As materiales

End Class
